# Generated by Django 4.2.2 on 2023-07-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=1000)),
                ("password1", models.CharField(max_length=8)),
                ("password2", models.CharField(max_length=8)),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
            ],
        ),
    ]
