# Generated by Django 4.2.2 on 2023-07-07 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("APP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="Personal_details",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
